version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli@6.0.8
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build
  post_build:
    commands:
      - aws s3 sync dist/ s3://diennt-pipeline --acl 'public-read' --delete
artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: build-artifact
  discard-paths: no
