version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g @angular/cli
  build:
    commands:
      - ng build
  post_build:
    commands:
      - aws s3 sync dist/ s3://diennt-pipeline --delete
